exclude:
  - src/test.ts
  - 'src/**/*.spec.ts'
  - 'projects/**/*.spec.ts'
  - config/
  - db/
  - dist/y
  - features/
  - '**/node_modules/'
  - script/
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - Tests/
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
  - '**/*.spec.ts'

plugins:
  duplication:
    enabled: false
