import {
  access,
  access2,
  activeDeactivate,
  add,
  addSecurity,
  addTelephone,
  addUser,
  alarmClock,
  alarmClockCheck,
  alarmClockMinus,
  alarmClockOff,
  alarmClockPlus,
  alert,
  alertList,
  alertTelephone,
  alertUser,
  announcement,
  arrowsDownUp,
  arrowsLeftRight,
  arrowsUpDown,
  auditForwarded,
  award,
  award2,
  bank,
  bankNote,
  barChartSquareDown,
  barChartSquareMinus,
  barChartSquarePlus,
  barChartSquareUp,
  barCode,
  batteryCharging,
  bellOff,
  bellRinging,
  block,
  bookOpen,
  box,
  box2,
  box3,
  box4,
  box5,
  box6,
  boxBlock,
  boxClock,
  boxLeft,
  boxMinus,
  boxPin,
  boxPlus,
  boxSearch,
  boxX,
  brokenFiber,
  business,
  calendar,
  calendarAdd,
  calendarAttention,
  calendarBlock,
  calendarCheck,
  calendarCheck2,
  calendarDate,
  calendarHeart,
  calendarHeart2,
  calendarMarker,
  calendarMinus,
  calendarMinus2,
  calendarMoney,
  calendarPlus,
  calendarPlus2,
  calendarReserved,
  calendarX,
  camera,
  camera2,
  cameraOff,
  car,
  certificate,
  change,
  changePriority,
  check,
  checkList,
  checkOutlined,
  checkSolid,
  checkUser,
  checkVerified,
  click,
  click2,
  clip,
  clipboard,
  clipboardAlert,
  clipboardCheck,
  clipboardLocalization,
  clipboardPlus,
  clipboardX,
  clock,
  clockCheck,
  clockFastFoward,
  clockPlus,
  clockRefresh,
  clockRewind,
  clockSnooze,
  clockSolid,
  clockStopwatch,
  close,
  closeRounded,
  closeSolid,
  cloud,
  cloudDownload,
  cloudUpload,
  coinsHand,
  comeIn,
  comment,
  condominium,
  condominium2,
  config,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  coreSwitch,
  cpe,
  creditCard,
  creditCardCheck,
  creditCardLock,
  creditCardPlus,
  creditCardShield,
  creditCardX,
  cto,
  cursor,
  database,
  diamond,
  displace,
  divide,
  doc,
  docAdd,
  docBar,
  docCheck,
  docClose,
  docDownload,
  docEmpty,
  docGraphic,
  docQuestion,
  docSearch,
  docWarning,
  down,
  down3,
  download,
  edit2,
  exclamation,
  exclamationRounded,
  exclamationSolid,
  expand,
  faceFrown,
  faceHappy,
  faceId,
  faceNeutral,
  faceSad,
  faceSmile,
  fan,
  fastBackward,
  fastForward,
  fiber,
  fileLock,
  fileShield,
  filter,
  fingerprint,
  flag,
  forwardedService,
  gift,
  globe1,
  globe2,
  graphic,
  graphic2,
  graphic3,
  group,
  hand,
  headset,
  heart,
  heartHand,
  historic,
  home,
  homeCheck,
  homeDown,
  homeLocalization,
  homeUp,
  homeUpdate,
  homeX,
  hook,
  horizontal,
  horizontalBarChart,
  hourglass,
  hourglass2,
  hourglass3,
  image,
  imageCheck,
  imageDown,
  imageLeft,
  imagePlus,
  imageRight,
  imageUp,
  imageUser,
  imageUserCheck,
  imageUserDown,
  imageUserPlus,
  imageUserX,
  imageX,
  inbox,
  info,
  information,
  infoSolid,
  intermittent,
  intersection,
  key,
  laptop,
  layoutAlt,
  layoutBottom,
  layoutGrid,
  layoutGrid2,
  layoutLeft,
  layoutRight,
  left,
  left2,
  left3,
  lightbulb,
  lineChartDown,
  lineChartUp,
  link,
  linkBroken,
  list,
  list2,
  listX,
  localization,
  lock,
  lockPlus,
  lockUnlocked,
  mail,
  map,
  markerPin,
  maximize,
  messageAlert,
  messageBallon,
  messageChat,
  messageCheck,
  messageHeart,
  messagePlus,
  messageQuestionCircle,
  messageText,
  messageX,
  microphone,
  microphoneOff,
  minimize,
  modem,
  module,
  moduleBox,
  money,
  monitor,
  moon,
  more,
  motorcycle,
  move,
  negotiation,
  negotiationBlock,
  netflix,
  notification,
  olt,
  onu,
  option,
  orderBottom,
  orderGeneric,
  orderLetter1,
  orderLetter2,
  orderNumber1,
  orderNumber2,
  orderUp,
  out,
  passcode,
  pastor,
  pause,
  pencil,
  percent,
  phoneBlock,
  phoneCall,
  phoneCall2,
  phoneHangUp,
  phoneIncoming,
  phoneOutgoing,
  phoneOutgoing1,
  phonePause,
  phoneRefresh,
  photo,
  pin,
  pin2,
  pix,
  play,
  plus,
  plusSolid,
  pon,
  presentationChart,
  printer,
  process,
  qrcode,
  questionRounded,
  radio,
  receipt,
  receiptCheck,
  receiveTelephone,
  recording1,
  recording2,
  refresh,
  regions,
  registrationList,
  removeTelephone,
  removeUser,
  repeat,
  restore,
  right,
  right2,
  right3,
  rota,
  sale,
  sandwich,
  save,
  scan,
  search,
  searchLocalization,
  security,
  semiDown,
  semiUp,
  send,
  serial,
  server,
  serviceCard,
  serviceInternet,
  servicePhone,
  serviceTv,
  share,
  shield,
  shieldOff,
  shieldTick,
  shoppingCart,
  shoppingCart2,
  simcard,
  smartphone,
  sortAsc,
  sortDesc,
  sparkle,
  speedometer,
  star,
  starSolid,
  stb,
  stop,
  sub,
  submit,
  sun,
  table,
  tag,
  tagDivision,
  target,
  target3,
  technical,
  telephone,
  thumbsDown,
  thumbsUp,
  ticket,
  time,
  timeTelephone,
  total,
  trash,
  trophy,
  tv,
  union,
  up,
  up3,
  upload,
  user,
  userBlock,
  userBottom,
  userClock,
  userLeft,
  userMarker,
  userMinus,
  userRight,
  userSearch,
  userTop,
  verificationSecurity,
  vertical,
  view,
  viewBlock,
  volumeMax,
  volumeMinus,
  volumePlus,
  volumeX,
  wait,
  waitCheck,
  waitWarning,
  wallet,
  watchCircle,
  watchSquare,
  whatsapp,
  wifi,
  wifiOff,
  workBag,
  working,
  zap,
  zapOff,
  zoomIn,
  zoomOut,
} from './iconsText';

// To add an icon, use kebab-case on key name and insert only SVG paths on value
export const iconsPaths: Record<string, string> = {
  access,
  access2,
  'active-deactivate': activeDeactivate,
  add,
  'add-security': addSecurity,
  'add-telephone': addTelephone,
  'add-user': addUser,
  'alarm-clock': alarmClock,
  'alarm-clock-check': alarmClockCheck,
  'alarm-clock-minus': alarmClockMinus,
  'alarm-clock-off': alarmClockOff,
  'alarm-clock-plus': alarmClockPlus,
  alert,
  'alert-list': alertList,
  'alert-telephone': alertTelephone,
  'alert-user': alertUser,
  announcement,
  'arrows-down-up': arrowsDownUp,
  'arrows-left-right': arrowsLeftRight,
  'arrows-up-down': arrowsUpDown,
  auditForwarded,
  award,
  award2,
  bank,
  'bank-note': bankNote,
  'bar-chart-square-down': barChartSquareDown,
  'bar-chart-square-minus': barChartSquareMinus,
  'bar-chart-square-plus': barChartSquarePlus,
  'bar-chart-square-up': barChartSquareUp,
  'bar-code': barCode,
  'battery-charging': batteryCharging,
  'bell-off': bellOff,
  'bell-ringing': bellRinging,
  block,
  'book-open': bookOpen,
  box,
  box2,
  box3,
  box4,
  box5,
  box6,
  'box-block': boxBlock,
  'box-clock': boxClock,
  'box-left': boxLeft,
  'box-minus': boxMinus,
  'box-pin': boxPin,
  'box-plus': boxPlus,
  'box-search': boxSearch,
  'box-x': boxX,
  'broken-fiber': brokenFiber,
  business,
  calendar,
  'calendar-add': calendarAdd,
  'calendar-attention': calendarAttention,
  'calendar-block': calendarBlock,
  'calendar-check': calendarCheck,
  'calendar-check2': calendarCheck2,
  'calendar-date': calendarDate,
  'calendar-heart': calendarHeart,
  'calendar-heart2': calendarHeart2,
  'calendar-marker': calendarMarker,
  'calendar-minus': calendarMinus,
  'calendar-minus2': calendarMinus2,
  'calendar-money': calendarMoney,
  'calendar-plus': calendarPlus,
  'calendar-plus2': calendarPlus2,
  'calendar-reserved': calendarReserved,
  'calendar-x': calendarX,
  camera,
  camera2,
  'camera-off': cameraOff,
  car,
  certificate,
  change,
  'change-priority': changePriority,
  check,
  'check-list': checkList,
  'check-outlined': checkOutlined,
  'check-solid': checkSolid,
  'check-user': checkUser,
  'check-verified': checkVerified,
  click,
  click2,
  clip,
  clipboard,
  'clipboard-alert': clipboardAlert,
  'clipboard-check': clipboardCheck,
  'clipboard-localization': clipboardLocalization,
  'clipboard-plus': clipboardPlus,
  'clipboard-x': clipboardX,
  clock,
  'clock-check': clockCheck,
  'clock-fast-foward': clockFastFoward,
  'clock-plus': clockPlus,
  'clock-refresh': clockRefresh,
  'clock-rewind': clockRewind,
  'clock-snooze': clockSnooze,
  'clock-solid': clockSolid,
  'clock-stopwatch': clockStopwatch,
  close,
  'close-rounded': closeRounded,
  'close-solid': closeSolid,
  cloud,
  'cloud-download': cloudDownload,
  'cloud-upload': cloudUpload,
  'coins-hand': coinsHand,
  'come-in': comeIn,
  comment,
  condominium,
  condominium2,
  config,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  'core-switch': coreSwitch,
  cpe,
  'credit-card': creditCard,
  'credit-card-check': creditCardCheck,
  'credit-card-lock': creditCardLock,
  'credit-card-plus': creditCardPlus,
  'credit-card-shield': creditCardShield,
  'credit-card-x': creditCardX,
  cto,
  cursor,
  database,
  diamond,
  displace,
  divide,
  doc,
  'doc-add': docAdd,
  'doc-bar': docBar,
  'doc-check': docCheck,
  'doc-close': docClose,
  'doc-download': docDownload,
  'doc-empty': docEmpty,
  'doc-graphic': docGraphic,
  'doc-question': docQuestion,
  'doc-search': docSearch,
  'doc-warning': docWarning,
  down,
  down3,
  download,
  edit2,
  exclamation,
  'exclamation-rounded': exclamationRounded,
  'exclamation-solid': exclamationSolid,
  expand,
  'face-frown': faceFrown,
  'face-happy': faceHappy,
  'face-id': faceId,
  'face-neutral': faceNeutral,
  'face-sad': faceSad,
  'face-smile': faceSmile,
  fan,
  'fast-backward': fastBackward,
  'fast-forward': fastForward,
  fiber,
  'file-lock': fileLock,
  'file-shield': fileShield,
  filter,
  fingerprint,
  flag,
  'forwarded-service': forwardedService,
  gift,
  globe1,
  globe2,
  graphic,
  graphic2,
  graphic3,
  group,
  hand,
  headset,
  heart,
  'heart-hand': heartHand,
  historic,
  home,
  'home-check': homeCheck,
  'home-down': homeDown,
  'home-localization': homeLocalization,
  'home-up': homeUp,
  'home-update': homeUpdate,
  'home-x': homeX,
  hook,
  horizontal,
  'horizontal-bar-chart': horizontalBarChart,
  hourglass,
  hourglass2,
  hourglass3,
  image,
  'image-check': imageCheck,
  'image-down': imageDown,
  'image-left': imageLeft,
  'image-plus': imagePlus,
  'image-right': imageRight,
  'image-up': imageUp,
  'image-user': imageUser,
  'image-user-check': imageUserCheck,
  'image-user-down': imageUserDown,
  'image-user-plus': imageUserPlus,
  'image-user-x': imageUserX,
  'image-x': imageX,
  inbox,
  info,
  'info-solid': infoSolid,
  information,
  intermittent,
  intersection,
  key,
  laptop,
  'layout-alt': layoutAlt,
  'layout-bottom': layoutBottom,
  'layout-grid': layoutGrid,
  'layout-grid2': layoutGrid2,
  'layout-left': layoutLeft,
  'layout-right': layoutRight,
  left,
  left2,
  left3,
  lightbulb,
  'line-chart-down': lineChartDown,
  'line-chart-up': lineChartUp,
  link,
  'link-broken': linkBroken,
  list,
  list2,
  'list-x': listX,
  localization,
  lock,
  'lock-plus': lockPlus,
  'lock-unlocked': lockUnlocked,
  mail,
  map,
  'marker-pin': markerPin,
  maximize,
  'message-alert': messageAlert,
  'message-ballon': messageBallon,
  'message-chat': messageChat,
  'message-check': messageCheck,
  'message-heart': messageHeart,
  'message-plus': messagePlus,
  'message-question-circle': messageQuestionCircle,
  'message-text': messageText,
  'message-x': messageX,
  microphone,
  'microphone-off': microphoneOff,
  minimize,
  modem,
  module,
  'module-box': moduleBox,
  money,
  monitor,
  moon,
  more,
  motorcycle,
  move,
  negotiation,
  'negotiation-block': negotiationBlock,
  netflix,
  notification,
  olt,
  onu,
  option,
  'order-bottom': orderBottom,
  'order-generic': orderGeneric,
  'order-letter1': orderLetter1,
  'order-letter2': orderLetter2,
  'order-number1': orderNumber1,
  'order-number2': orderNumber2,
  'order-up': orderUp,
  out,
  passcode,
  pastor,
  pause,
  pencil,
  percent,
  'phone-block': phoneBlock,
  'phone-call': phoneCall,
  'phone-call2': phoneCall2,
  'phone-hang-up': phoneHangUp,
  'phone-incoming': phoneIncoming,
  'phone-outgoing': phoneOutgoing,
  'phone-outgoing1': phoneOutgoing1,
  'phone-pause': phonePause,
  'phone-refresh': phoneRefresh,
  photo,
  pin,
  pin2,
  pix,
  play,
  plus,
  'plus-solid': plusSolid,
  pon,
  'presentation-chart': presentationChart,
  printer,
  process,
  qrcode,
  'question-rounded': questionRounded,
  radio,
  receipt,
  'receipt-check': receiptCheck,
  'receive-telephone': receiveTelephone,
  recording1,
  recording2,
  refresh,
  regions,
  'registration-list': registrationList,
  'remove-telephone': removeTelephone,
  'remove-user': removeUser,
  repeat,
  restore,
  right,
  right2,
  right3,
  rota,
  sale,
  sandwich,
  save,
  scan,
  search,
  'search-localization': searchLocalization,
  security,
  'semi-down': semiDown,
  'semi-up': semiUp,
  send,
  serial,
  server,
  'service-card': serviceCard,
  'service-internet': serviceInternet,
  'service-phone': servicePhone,
  'service-tv': serviceTv,
  share,
  shield,
  'shield-off': shieldOff,
  'shield-tick': shieldTick,
  'shopping-cart': shoppingCart,
  'shopping-cart-2': shoppingCart2,
  simcard,
  smartphone,
  'sort-asc': sortAsc,
  'sort-desc': sortDesc,
  sparkle,
  speedometer,
  star,
  'star-solid': starSolid,
  stb,
  stop,
  sub,
  submit,
  sun,
  table,
  tag,
  'tag-division': tagDivision,
  target,
  target3,
  technical,
  telephone,
  'thumbs-down': thumbsDown,
  'thumbs-up': thumbsUp,
  ticket,
  time,
  'time-telephone': timeTelephone,
  total,
  trash,
  trophy,
  tv,
  union,
  up,
  up3,
  upload,
  user,
  'user-block': userBlock,
  'user-bottom': userBottom,
  'user-clock': userClock,
  'user-left': userLeft,
  'user-marker': userMarker,
  'user-minus': userMinus,
  'user-right': userRight,
  'user-search': userSearch,
  'user-top': userTop,
  'verification-security': verificationSecurity,
  vertical,
  view,
  'view-block': viewBlock,
  'volume-max': volumeMax,
  'volume-minus': volumeMinus,
  'volume-plus': volumePlus,
  'volume-x': volumeX,
  wait,
  'wait-check': waitCheck,
  'wait-warning': waitWarning,
  wallet,
  'watch-circle': watchCircle,
  'watch-square': watchSquare,
  whatsapp,
  wifi,
  'wifi-off': wifiOff,
  'work-bag': workBag,
  working,
  zap,
  'zap-off': zapOff,
  'zoom-in': zoomIn,
  'zoom-out': zoomOut,
};
