import {
  access,
  access2,
  activeDeactivate,
  activity,
  activityHeart,
  add,
  addSecurity,
  addTelephone,
  addUser,
  alarmClock,
  alarmClockCheck,
  alarmClockMinus,
  alarmClockOff,
  alarmClockPlus,
  alert,
  alertList,
  alertTelephone,
  alertUser,
  anchor,
  announcement,
  archive,
  arrowsDownUp,
  arrowsLeftRight,
  arrowsUpDown,
  asterisk,
  asterisk2,
  atSign,
  auditForwarded,
  award,
  award2,
  bank,
  bankNote,
  barChartSquareDown,
  barChartSquareMinus,
  barChartSquarePlus,
  barChartSquareUp,
  barCode,
  batteryCharging,
  bellOff,
  bellRinging,
  block,
  bookmark,
  bookmarkAdd,
  bookmarkCheck,
  bookmarkMinus,
  bookmarkX,
  bookOpen,
  box,
  box2,
  box3,
  box4,
  box5,
  box6,
  boxBlock,
  boxClock,
  boxLeft,
  boxMinus,
  boxPin,
  boxPlus,
  boxSearch,
  boxX,
  brokenFiber,
  building,
  building2,
  building3,
  building4,
  building5,
  building6,
  building7,
  building8,
  business,
  calendar,
  calendarAdd,
  calendarAttention,
  calendarBlock,
  calendarCheck,
  calendarMarker,
  calendarMoney,
  calendarReserved,
  calendarX,
  camera,
  camera2,
  cameraOff,
  car,
  certificate,
  change,
  changePriority,
  check,
  checkCircle,
  checkCircleBroken,
  checkDone,
  checkDone2,
  checkHeart,
  checkList,
  checkOutlined,
  checkSolid,
  checkSquare,
  checkSquareBroken,
  checkUser,
  checkVerified,
  checkVerified2,
  checkVerified3,
  click,
  click2,
  clip,
  clipboard,
  clipboardAlert,
  clipboardCheck,
  clipboardLocalization,
  clipboardPlus,
  clipboardX,
  clockPlus,
  clockSnooze,
  clockSolid,
  clockStopwatch,
  close,
  closeRounded,
  closeSolid,
  cloud,
  cloudBlank,
  cloudBlank2,
  cloudDownload,
  cloudUpload,
  coinsHand,
  comeIn,
  comment,
  condominium,
  condominium2,
  config,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  copy2,
  copy3,
  copy4,
  copy5,
  copy6,
  copy7,
  coreSwitch,
  cpe,
  creditCard,
  creditCardCheck,
  creditCardLock,
  creditCardPlus,
  creditCardShield,
  creditCardX,
  cto,
  cursor,
  database,
  diamond,
  displace,
  divide,
  divide2,
  divide3,
  doc,
  docAdd,
  docBar,
  docCheck,
  docClose,
  docDownload,
  docEmpty,
  docGraphic,
  docQuestion,
  docSearch,
  docWarning,
  dotsGrid,
  dotsHorizontal,
  dotsVertical,
  down,
  down3,
  download,
  download2,
  download3,
  download4,
  downloadCloud,
  downloadCloud2,
  edit,
  edit2,
  edit3,
  edit4,
  edit5,
  equal,
  equalNot,
  exclamation,
  exclamationRounded,
  exclamationSolid,
  expand,
  eye,
  eyeOff,
  faceFrown,
  faceHappy,
  faceId,
  faceNeutral,
  faceSad,
  faceSmile,
  fan,
  fastBackward,
  fastForward,
  fiber,
  fileLock,
  fileShield,
  filter,
  filterFunnel,
  filterFunnel2,
  filterLines,
  fingerprint,
  flag,
  forwardedService,
  gift,
  globe1,
  globe2,
  googleChrome,
  graphic,
  graphic2,
  graphic3,
  group,
  hand,
  hash,
  hash2,
  headset,
  heart,
  heartCircle,
  heartHand,
  heartHexagon,
  heartOctagon,
  heartRounded,
  hearts,
  heartSquare,
  helpCircle,
  helpHexagon,
  helpOctagon,
  helpSquare,
  historic,
  home,
  home2,
  home3,
  home4,
  home5,
  homeCheck,
  homeDown,
  homeLine,
  homeLocalization,
  homeSmile,
  homeUp,
  homeUpdate,
  homeX,
  hook,
  horizontal,
  horizontalBarChart,
  image,
  imageCheck,
  imageDown,
  imageLeft,
  imagePlus,
  imageRight,
  imageUp,
  imageUser,
  imageUserCheck,
  imageUserDown,
  imageUserPlus,
  imageUserX,
  imageX,
  inbox,
  info,
  infoCircle,
  infoHexagon,
  infoOctagon,
  infoSolid,
  information,
  infoSquare,
  intermittent,
  intersection,
  key,
  laptop,
  layoutAlt,
  layoutBottom,
  layoutGrid,
  layoutGrid2,
  layoutLeft,
  layoutRight,
  left,
  left2,
  left3,
  lifeBuoy,
  lifeBuoy2,
  lightbulb,
  lineChartDown,
  lineChartUp,
  link,
  link2,
  link3,
  link4,
  link5,
  linkBroken,
  linkBroken2,
  linkExternal,
  linkExternal2,
  list,
  list2,
  listX,
  loading,
  loading2,
  loading3,
  localization,
  lock,
  lockPlus,
  lockUnlocked,
  logIn,
  logIn2,
  logIn3,
  logIn4,
  logOut,
  logOut2,
  logOut3,
  logOut4,
  mail,
  map,
  markerPin,
  maximize,
  medicalCircle,
  medicalCross,
  medicalSquare,
  menu,
  menu2,
  menu3,
  menu4,
  menu5,
  messageAlert,
  messageBallon,
  messageChat,
  messageCheck,
  messageHeart,
  messagePlus,
  messageQuestionCircle,
  messageText,
  messageX,
  microphone,
  microphoneOff,
  minimize,
  minus,
  minusCircle,
  minusSquare,
  modem,
  module,
  moduleBox,
  money,
  monitor,
  moon,
  more,
  motorcycle,
  move,
  negotiation,
  negotiationBlock,
  netflix,
  notification,
  olt,
  onu,
  option,
  orderBottom,
  orderGeneric,
  orderLetter1,
  orderLetter2,
  orderNumber1,
  orderNumber2,
  orderUp,
  out,
  passcode,
  pastor,
  pause,
  pencil,
  percent,
  percent2,
  percent3,
  phoneBlock,
  phoneCall,
  phoneCall2,
  phoneHangUp,
  phoneIncoming,
  phoneOutgoing,
  phoneOutgoing1,
  phonePause,
  phoneRefresh,
  photo,
  pin,
  pin2,
  pix,
  placeholder,
  play,
  plus,
  plusCircle,
  plusSolid,
  plusSquare,
  pon,
  presentationChart,
  printer,
  process,
  qrcode,
  questionRounded,
  radio,
  receipt,
  receiptCheck,
  receiveTelephone,
  recording1,
  recording2,
  refresh,
  regions,
  registrationList,
  removeTelephone,
  removeUser,
  repeat,
  restore,
  right,
  right2,
  right3,
  rota,
  sale,
  sandwich,
  save,
  save2,
  save3,
  scan,
  search,
  searchLg,
  searchLocalization,
  searchMd,
  searchRefraction,
  searchSm,
  security,
  semiDown,
  semiUp,
  send,
  serial,
  server,
  serviceCard,
  serviceInternet,
  servicePhone,
  serviceTv,
  settings,
  settings2,
  settings3,
  settings4,
  share,
  share2,
  share3,
  share4,
  share5,
  share6,
  share7,
  shield,
  shieldOff,
  shieldTick,
  shoppingCart,
  shoppingCart2,
  simcard,
  slashCircle,
  slashCircle2,
  slashDivider,
  slashOctagon,
  smartphone,
  sortAsc,
  sortDesc,
  sparkle,
  speedometer,
  speedometer2,
  speedometer3,
  speedometer4,
  star,
  starSolid,
  stb,
  stop,
  sub,
  submit,
  sun,
  table,
  tag,
  tagDivision,
  target,
  target2,
  target3,
  target4,
  target5,
  technical,
  telephone,
  thumbsDown,
  thumbsUp,
  ticket,
  time,
  timeTelephone,
  toggle2Left,
  toggle2Right,
  toggle3Left,
  toggle3Right,
  toggleLeft,
  toggleRight,
  tool,
  tool2,
  total,
  translate,
  translate2,
  trash,
  trash2,
  trash3,
  trash4,
  trophy,
  tv,
  union,
  up,
  up3,
  upload,
  upload2,
  upload3,
  upload4,
  uploadCloud,
  uploadCloud2,
  user,
  userBlock,
  userBottom,
  userClock,
  userLeft,
  userMarker,
  userMinus,
  userRight,
  userSearch,
  userTop,
  verificationSecurity,
  vertical,
  view,
  viewBlock,
  virus,
  volumeMax,
  volumeMinus,
  volumePlus,
  volumeX,
  wait,
  waitCheck,
  waitWarning,
  wallet,
  watchCircle,
  whatsapp,
  wifi,
  wifiOff,
  workBag,
  working,
  x,
  xCircle,
  xClose,
  xSquare,
  zap,
  zapCircle,
  zapFast,
  zapOff,
  zapSquare,
  zoomIn,
  zoomOut,
} from './iconsText';

// To add an icon, use kebab-case on key name and insert only SVG paths on value
export const iconsPaths: Record<string, string> = {
  access,
  access2,
  'active-deactivate': activeDeactivate,
  activity,
  'activity-heart': activityHeart,
  add,
  'add-security': addSecurity,
  'add-telephone': addTelephone,
  'add-user': addUser,
  'alarm-clock': alarmClock,
  'alarm-clock-check': alarmClockCheck,
  'alarm-clock-minus': alarmClockMinus,
  'alarm-clock-off': alarmClockOff,
  'alarm-clock-plus': alarmClockPlus,
  alert,
  'alert-list': alertList,
  'alert-telephone': alertTelephone,
  'alert-user': alertUser,
  anchor,
  announcement,
  archive,
  'arrows-down-up': arrowsDownUp,
  'arrows-left-right': arrowsLeftRight,
  'arrows-up-down': arrowsUpDown,
  asterisk,
  asterisk2,
  'at-sign': atSign,
  auditForwarded,
  award,
  award2,
  bank,
  'bank-note': bankNote,
  'bar-chart-square-down': barChartSquareDown,
  'bar-chart-square-minus': barChartSquareMinus,
  'bar-chart-square-plus': barChartSquarePlus,
  'bar-chart-square-up': barChartSquareUp,
  'bar-code': barCode,
  'battery-charging': batteryCharging,
  'bell-off': bellOff,
  'bell-ringing': bellRinging,
  block,
  'book-open': bookOpen,
  bookmark,
  'bookmark-add': bookmarkAdd,
  'bookmark-check': bookmarkCheck,
  'bookmark-minus': bookmarkMinus,
  'bookmark-x': bookmarkX,
  box,
  box2,
  box3,
  box4,
  box5,
  box6,
  'box-block': boxBlock,
  'box-clock': boxClock,
  'box-left': boxLeft,
  'box-minus': boxMinus,
  'box-pin': boxPin,
  'box-plus': boxPlus,
  'box-search': boxSearch,
  'box-x': boxX,
  'broken-fiber': brokenFiber,
  building,
  building2,
  building3,
  building4,
  building5,
  building6,
  building7,
  building8,
  business,
  calendar,
  'calendar-add': calendarAdd,
  'calendar-attention': calendarAttention,
  'calendar-block': calendarBlock,
  'calendar-check': calendarCheck,
  'calendar-marker': calendarMarker,
  'calendar-money': calendarMoney,
  'calendar-reserved': calendarReserved,
  'calendar-x': calendarX,
  camera,
  camera2,
  'camera-off': cameraOff,
  car,
  certificate,
  change,
  check,
  'change-priority': changePriority,
  'check-circle': checkCircle,
  'check-circle-broken': checkCircleBroken,
  'check-done': checkDone,
  'check-done2': checkDone2,
  'check-heart': checkHeart,
  'check-list': checkList,
  'check-outlined': checkOutlined,
  'check-solid': checkSolid,
  'check-square': checkSquare,
  'check-square-broken': checkSquareBroken,
  'check-user': checkUser,
  'check-verified': checkVerified,
  'check-verified2': checkVerified2,
  'check-verified3': checkVerified3,
  click,
  click2,
  clip,
  clipboard,
  'clipboard-alert': clipboardAlert,
  'clipboard-check': clipboardCheck,
  'clipboard-localization': clipboardLocalization,
  'clipboard-plus': clipboardPlus,
  'clipboard-x': clipboardX,
  'clock-plus': clockPlus,
  'clock-snooze': clockSnooze,
  'clock-solid': clockSolid,
  'clock-stopwatch': clockStopwatch,
  close,
  'close-rounded': closeRounded,
  'close-solid': closeSolid,
  'cloud-blank': cloudBlank,
  'cloud-blank2': cloudBlank2,
  cloud,
  'cloud-download': cloudDownload,
  'cloud-upload': cloudUpload,
  'coins-hand': coinsHand,
  'come-in': comeIn,
  comment,
  condominium,
  condominium2,
  config,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  copy2,
  copy3,
  copy4,
  copy5,
  copy6,
  copy7,
  'core-switch': coreSwitch,
  cpe,
  'credit-card': creditCard,
  'credit-card-check': creditCardCheck,
  'credit-card-lock': creditCardLock,
  'credit-card-plus': creditCardPlus,
  'credit-card-shield': creditCardShield,
  'credit-card-x': creditCardX,
  cto,
  cursor,
  database,
  diamond,
  displace,
  divide,
  divide2,
  divide3,
  doc,
  'doc-add': docAdd,
  'doc-bar': docBar,
  'doc-check': docCheck,
  'doc-close': docClose,
  'doc-download': docDownload,
  'doc-empty': docEmpty,
  'doc-graphic': docGraphic,
  'doc-question': docQuestion,
  'doc-search': docSearch,
  'doc-warning': docWarning,
  'dots-grid': dotsGrid,
  'dots-horizontal': dotsHorizontal,
  'dots-vertical': dotsVertical,
  down,
  down3,
  download,
  'download-cloud': downloadCloud,
  'download-cloud2': downloadCloud2,
  download2,
  download3,
  download4,
  edit,
  edit2,
  edit3,
  edit4,
  edit5,
  equal,
  'equal-not': equalNot,
  exclamation,
  'exclamation-rounded': exclamationRounded,
  'exclamation-solid': exclamationSolid,
  expand,
  eye,
  'eye-off': eyeOff,
  'face-frown': faceFrown,
  'face-happy': faceHappy,
  'face-id': faceId,
  'face-neutral': faceNeutral,
  'face-sad': faceSad,
  'face-smile': faceSmile,
  fan,
  'fast-backward': fastBackward,
  'fast-forward': fastForward,
  fiber,
  'file-lock': fileLock,
  'file-shield': fileShield,
  filter,
  'filter-funnel': filterFunnel,
  'filter-funnel2': filterFunnel2,
  'filter-lines': filterLines,
  fingerprint,
  flag,
  'forwarded-service': forwardedService,
  gift,
  globe1,
  globe2,
  'google-chrome': googleChrome,
  graphic,
  graphic2,
  graphic3,
  group,
  hand,
  hash,
  hash2,
  headset,
  heart,
  hearts,
  'heart-circle': heartCircle,
  'heart-hand': heartHand,
  'heart-hexagon': heartHexagon,
  'heart-octagon': heartOctagon,
  'heart-rounded': heartRounded,
  'heart-square': heartSquare,
  'help-circle': helpCircle,
  historic,
  home,
  home2,
  home3,
  home4,
  home5,
  'home-check': homeCheck,
  'home-down': homeDown,
  'home-line': homeLine,
  'home-localization': homeLocalization,
  'home-smile': homeSmile,
  'home-up': homeUp,
  'home-update': homeUpdate,
  'home-x': homeX,
  hook,
  horizontal,
  'horizontal-bar-chart': horizontalBarChart,
  image,
  'image-check': imageCheck,
  'image-down': imageDown,
  'image-left': imageLeft,
  'image-plus': imagePlus,
  'image-right': imageRight,
  'image-up': imageUp,
  'image-user': imageUser,
  'image-user-check': imageUserCheck,
  'image-user-down': imageUserDown,
  'image-user-plus': imageUserPlus,
  'image-user-x': imageUserX,
  'image-x': imageX,
  inbox,
  info,
  'info-circle': infoCircle,
  'info-hexagon': infoHexagon,
  'info-octagon': infoOctagon,
  'info-solid': infoSolid,
  'info-square': infoSquare,
  information,
  intermittent,
  intersection,
  key,
  laptop,
  'layout-alt': layoutAlt,
  'layout-bottom': layoutBottom,
  'layout-grid': layoutGrid,
  'layout-grid2': layoutGrid2,
  'layout-left': layoutLeft,
  'layout-right': layoutRight,
  left,
  left2,
  left3,
  'life-buoy': lifeBuoy,
  'life-buoy2': lifeBuoy2,
  lightbulb,
  'line-chart-down': lineChartDown,
  'line-chart-up': lineChartUp,
  link,
  link2,
  link3,
  link4,
  link5,
  'link-broken': linkBroken,
  'link-broken2': linkBroken2,
  'link-external': linkExternal,
  'link-external2': linkExternal2,
  list,
  list2,
  'list-x': listX,
  loading,
  loading2,
  loading3,
  localization,
  lock,
  'lock-plus': lockPlus,
  'lock-unlocked': lockUnlocked,
  'log-in': logIn,
  'log-in2': logIn2,
  'log-in3': logIn3,
  'log-in4': logIn4,
  'log-out': logOut,
  'log-out2': logOut2,
  'log-out3': logOut3,
  'log-out4': logOut4,
  mail,
  map,
  'marker-pin': markerPin,
  maximize,
  'medical-circle': medicalCircle,
  'medical-cross': medicalCross,
  'medical-square': medicalSquare,
  menu,
  menu2,
  menu3,
  menu4,
  menu5,
  'message-alert': messageAlert,
  'message-ballon': messageBallon,
  'message-chat': messageChat,
  'message-check': messageCheck,
  'message-heart': messageHeart,
  'message-plus': messagePlus,
  'message-question-circle': messageQuestionCircle,
  'message-text': messageText,
  'message-x': messageX,
  microphone,
  'microphone-off': microphoneOff,
  minimize,
  minus,
  'minus-circle': minusCircle,
  'minus-square': minusSquare,
  modem,
  module,
  'module-box': moduleBox,
  money,
  monitor,
  moon,
  more,
  motorcycle,
  move,
  negotiation,
  'negotiation-block': negotiationBlock,
  netflix,
  notification,
  olt,
  onu,
  option,
  'order-bottom': orderBottom,
  'order-generic': orderGeneric,
  'order-letter1': orderLetter1,
  'order-letter2': orderLetter2,
  'order-number1': orderNumber1,
  'order-number2': orderNumber2,
  'order-up': orderUp,
  out,
  passcode,
  pastor,
  pause,
  pencil,
  percent,
  percent2,
  percent3,
  'phone-block': phoneBlock,
  'phone-call': phoneCall,
  'phone-call2': phoneCall2,
  'phone-hang-up': phoneHangUp,
  'phone-incoming': phoneIncoming,
  'phone-outgoing': phoneOutgoing,
  'phone-outgoing1': phoneOutgoing1,
  'phone-pause': phonePause,
  'phone-refresh': phoneRefresh,
  photo,
  pin,
  pin2,
  pix,
  placeholder,
  play,
  plus,
  'plus-circle': plusCircle,
  'plus-solid': plusSolid,
  'plus-square': plusSquare,
  'presentation-chart': presentationChart,
  pon,
  printer,
  process,
  qrcode,
  'question-rounded': questionRounded,
  radio,
  receipt,
  'receipt-check': receiptCheck,
  'receive-telephone': receiveTelephone,
  recording1,
  recording2,
  refresh,
  regions,
  'registration-list': registrationList,
  'remove-telephone': removeTelephone,
  'remove-user': removeUser,
  repeat,
  restore,
  right,
  right2,
  right3,
  rota,
  sale,
  sandwich,
  save,
  save2,
  save3,
  scan,
  search,
  'search-lg': searchLg,
  'search-localization': searchLocalization,
  'search-md': searchMd,
  'search-refraction': searchRefraction,
  'search-sm': searchSm,
  security,
  'semi-down': semiDown,
  'semi-up': semiUp,
  send,
  serial,
  server,
  'service-card': serviceCard,
  'service-internet': serviceInternet,
  'service-phone': servicePhone,
  'service-tv': serviceTv,
  settings,
  settings2,
  settings3,
  settings4,
  share,
  share2,
  share3,
  share4,
  share5,
  share6,
  share7,
  shield,
  'shield-off': shieldOff,
  'shield-tick': shieldTick,
  'shopping-cart': shoppingCart,
  'shopping-cart-2': shoppingCart2,
  simcard,
  'slash-circle': slashCircle,
  'slash-circle2': slashCircle2,
  'slash-divider': slashDivider,
  'slash-octagon': slashOctagon,
  smartphone,
  'sort-asc': sortAsc,
  'sort-desc': sortDesc,
  sparkle,
  speedometer,
  speedometer2,
  speedometer3,
  speedometer4,
  star,
  'star-solid': starSolid,
  stb,
  stop,
  sub,
  submit,
  sun,
  table,
  tag,
  'tag-division': tagDivision,
  target,
  target2,
  target3,
  target4,
  target5,
  technical,
  telephone,
  'thumbs-down': thumbsDown,
  'thumbs-up': thumbsUp,
  ticket,
  time,
  'time-telephone': timeTelephone,
  'toggle-left': toggleLeft,
  'toggle-right': toggleRight,
  'toggle2-left': toggle2Left,
  'toggle2-right': toggle2Right,
  'toggle3-left': toggle3Left,
  'toggle3-right': toggle3Right,
  tool,
  tool2,
  total,
  translate,
  translate2,
  trash,
  trash2,
  trash3,
  trash4,
  tv,
  trophy,
  union,
  up,
  up3,
  upload,
  'upload-cloud': uploadCloud,
  'upload-cloud2': uploadCloud2,
  upload2,
  upload3,
  upload4,
  user,
  'user-block': userBlock,
  'user-bottom': userBottom,
  'user-clock': userClock,
  'user-left': userLeft,
  'user-marker': userMarker,
  'user-minus': userMinus,
  'user-right': userRight,
  'user-search': userSearch,
  'user-top': userTop,
  'verification-security': verificationSecurity,
  vertical,
  view,
  virus,
  'view-block': viewBlock,
  'volume-max': volumeMax,
  'volume-minus': volumeMinus,
  'volume-plus': volumePlus,
  'volume-x': volumeX,
  wait,
  'wait-check': waitCheck,
  'wait-warning': waitWarning,
  wallet,
  'watch-circle': watchCircle,
  whatsapp,
  wifi,
  'wifi-off': wifiOff,
  'work-bag': workBag,
  working,
  x,
  'x-circle': xCircle,
  'x-close': xClose,
  'x-square': xSquare,
  zap,
  'zap-circle': zapCircle,
  'zap-fast': zapFast,
  'zap-off': zapOff,
  'zap-square': zapSquare,
  'zoom-in': zoomIn,
  'zoom-out': zoomOut,
};
