name: Automated Tests and Linting

on:
  pull_request:
    branches: ['main']

jobs:
  test-prettier-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.22.1]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test:coverage

      - uses: qltysh/qlty-action/coverage@v1
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        with:
          files: ./coverage/lcov.info

      - name: Run Prettier
        run: yarn prettier

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build
