name: CI
on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  yarn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.22.1]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn

  lint-prettier:
    runs-on: ubuntu-latest
    needs: yarn
    strategy:
      matrix:
        node-version: [12.22.1]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn lint
    - run: yarn prettier

  build:
    runs-on: ubuntu-latest
    needs: lint-prettier
    strategy:
      matrix:
        node-version: [12.22.1]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn run build
